name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or whichever branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # deploy the root directory (or adjust if your static files are in a subfolder)
